# Generated by Django 5.1.15 on 2026-07-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ai_profile_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="ai_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
