# Generated by Django 5.1.15 on 2026-07-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_profile_ai_profile_consent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="ai_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="ai_analysis_status",
            field=models.CharField(default="not_requested", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="ai_traits",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="IntroductionDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("discarded", "Discarded"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="introduction_drafts",
                        to="core.conversation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.profile"
                    ),
                ),
            ],
        ),
    ]
