# Generated by Django 5.1.15 on 2026-07-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auditevent_moderationevent_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deal_breakers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="life_goals",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="profile",
            name="lifestyle",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="MatchFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("good_fit", "Good fit"),
                            ("not_aligned", "Not aligned"),
                            ("great_conversation", "Great conversation"),
                            ("no_response", "No response"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="core.match",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.profile"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "profile"), name="unique_match_feedback"
                    )
                ],
            },
        ),
    ]
