# Generated by Django 5.1.15 on 2026-07-14 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_profile_deal_breakers_profile_life_goals_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="guidelines_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_18_or_older",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="report",
            name="resolution_notes",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="report",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("reviewing", "Reviewing"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
