# Generated by Django 5.1.15 on 2026-07-14 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_profile_guidelines_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sms_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="sms_match_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="sms_safety_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sms_unread_reminders",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PhoneCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("verify", "Verify phone"),
                            ("reset", "Reset password"),
                        ],
                        max_length=12,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_codes",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
