# Generated by Django 5.1.15 on 2026-07-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_notification_sms_sent_at_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_luna",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="luna_stage",
            field=models.CharField(default="welcome", max_length=24),
        ),
        migrations.AddField(
            model_name="conversation",
            name="pending_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="luna_inboxes",
                to="core.match",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="presented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="match",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="human_matches",
                to="core.conversation",
            ),
        ),
    ]
