# Generated by Django 4.2.30 on 2026-07-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_conversation_is_luna_conversation_luna_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_contact_sharing_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="ai_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DateMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_time", models.DateTimeField()),
                ("venue_name", models.CharField(max_length=160)),
                ("venue_address", models.CharField(max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_meetings",
                        to="core.conversation",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_dates",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
