# Generated by Django 4.2.30 on 2026-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_conversation_is_contact_sharing_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Man"), ("female", "Woman"), ("other", "Other")],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender_preference",
            field=models.CharField(
                blank=True,
                choices=[("male", "Men"), ("female", "Women"), ("both", "Everyone")],
                default="both",
                max_length=20,
            ),
        ),
    ]
