# Generated by Django 4.2.30 on 2026-07-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_conversation_is_counseling_profile_is_premium_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.UUIDField(unique=True)),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("processing", "Processing"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_payments",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
