# Generated by Django 4.2.30 on 2026-07-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_premiumpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.TextField(blank=True),
        ),
    ]
