# Generated by Django 4.2.30 on 2026-07-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="luna_board",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
