# Generated by Django 4.2.30 on 2026-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_conversation_luna_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="luna_presence_votes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
